nils_2_skills/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'Profile' => 'user#Profile'

  get 'Dashboard' => 'user#Dashboard'

  get 'MySkills' => 'user#MySkills'

  get 'Home' => 'static_pages#Home'

  get 'About' => 'static_pages#About'

  get 'Help' => 'static_pages#Help'

  get 'Settings' => 'static_pages#Settings'

  resources :development_plans
  resources :development_skills
  resources :skills
  resources :development_tasks
  resources :skill_categories
  resources :skill_levels

  root 'static_pages#Home'

end

nils_2_skills/app/models/development_skill.rb
class DevelopmentSkill < ActiveRecord::Base
  belongs_to :skill
  belongs_to :user
  belongs_to :development_plan
  belongs_to :current_skill_level, class_name: 'SkillLevel'
  belongs_to :desired_skill_level, class_name: 'SkillLevel'
  has_many :development_tasks
end

nils_2_skills/app/controllers/development_skills_controller.rb
class DevelopmentSkillsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_development_skill, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @development_skills = DevelopmentSkill.all
    respond_with(@development_skills)
  end

  def show
    respond_with(@development_skill)
  end

  def new
    @development_skill = DevelopmentSkill.new
    @skills = Skill.all
    @skill_levels = SkillLevel.all
    respond_with(@development_skill)
  end

  def edit
    @skills = Skill.all
    @skill_levels = SkillLevel.all
  end

  def create
    @development_skill = DevelopmentSkill.new(development_skill_params)
    @development_skill.user = current_user
    @development_skill.save
    respond_with(@development_skill)
  end

  def update
    @development_skill.update(development_skill_params)
    respond_with(@development_skill)
  end

  def destroy
    @development_skill.destroy
    respond_with(@development_skill)
  end

  private

  def set_development_skill
    @development_skill = DevelopmentSkill.find(params[:id])
  end

  def development_skill_params
    params.require(:development_skill).permit(:skill_id, :desired_skill_level_id, :notes, :completed, :percent_complete, :current_skill_level_id, :development_plan_id)
  end
end

nils_2_skills/app/helpers/development_skills_helper.rb
module DevelopmentSkillsHelper
end

nils_2_skills/app/views/development_skills/_form.html.erb
<%= form_for(@development_skill) do |f| %>
  <% if @development_skill.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(@development_skill.errors.count, 'error') %> prohibited this development_skill from being saved:</h2>

      <ul>
      <% @development_skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='field'>
    <%= f.label :skill_name %><br>
    <% options = options_from_collection_for_select(@skills, 'id','skill_name') %>
    <%= f.select :skill_id, options %>  
  </div>
  <div class='field'>
    <%= f.label :desired_skill_level %><br>    
    <%= collection_select(:development_skill, :desired_skill_level_id, SkillLevel.all, :id, :level) %>
  </div>
  <div class='field'>
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class='field'>
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <div class='field'>
    <%= f.label :percent_complete %><br>
    <%= f.text_field :percent_complete %>
  </div>
  <div class='field'>
    <%= f.label :current_skill_level %><br>
    <%= collection_select(:development_skill, :current_skill_level_id, SkillLevel.all, :id, :level) %>
  </div>
  <div class='field'>
    <%= f.label :development_plan_id %><br>
    <%= collection_select(:development_skill, :development_plan_id, current_user.development_plans, :id, :plan_name, :selected => params[:development_plan_id]) %> 
  </div>
  <div class='actions'>
    <%= f.submit %>
  </div>
<% end %>

nils_2_skills/app/views/development_skills/edit.html.erb
<h1>Editing development_skill</h1>

<%= render 'form' %>

<%= link_to 'Show', @development_skill %> |
<%= link_to 'Back', development_skills_path %>

nils_2_skills/app/views/development_skills/index.html.erb
<h1>Listing Development Skills</h1>

<table>
  <thead>
    <tr>
      <th>Skill name</th>
      <th>Desired skill level</th>
      <th>Notes</th>
      <th>Completed</th>
      <th>Percent complete</th>
      <th>Current skill level</th>
      <th>Development plan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @development_skills.each do |development_skill| %>
      <tr>
        <td><%= development_skill.skill.skill_name %></td>
        <td><%= development_skill.desired_skill_level.level %></td>
        <td><%= development_skill.notes %></td>
        <td><%= development_skill.completed %></td>
        <td><%= development_skill.percent_complete %></td>
        <td><%= development_skill.current_skill_level.level %></td>
        <td><%= DevelopmentPlan.find(development_skill.development_plan_id).plan_name %></td>
        <td><%= link_to 'Show', development_skill %></td>
        <td><%= link_to 'Edit', edit_development_skill_path(development_skill) %></td>
        <td><%= link_to 'Destroy', development_skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Development skill', new_development_skill_path %>

nils_2_skills/app/views/development_skills/new.html.erb
<h1>New development skill</h1>

<%= render 'form' %>

<%= link_to 'Back', development_skills_path %>

nils_2_skills/app/views/development_skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Skill name:</strong>
  <%= @development_skill.skill.skill_name %>
</p>

<p>
  <strong>Desired skill level:</strong>
  <%= @development_skill.desired_skill_level.level %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @development_skill.notes %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @development_skill.completed %>
</p>

<p>
  <strong>Percent complete:</strong>
  <%= @development_skill.percent_complete %>
</p>

<p>
  <strong>Current skill level:</strong>
  <%= @development_skill.current_skill_level.level %>
</p>

<p>
  <strong>Development plan:</strong>
  <%= DevelopmentPlan.find(@development_skill.development_plan_id).plan_name %>
</p>

<%= link_to 'Edit', edit_development_skill_path(@development_skill, :development_plan_id => @development_skill.development_plan_id) %> |
<%= link_to("New Development Task", new_development_task_path(:development_skill_id => @development_skill.id)) %><br/>
<p>
  <strong>Development Tasks:</strong>
  <%= DevelopmentTask.all %>
</p>
<%= link_to 'Back to skills', development_skills_path %> |
<%= link_to 'Back to development plan', development_plan_path(@development_skill.development_plan_id) %>