nils_2_skills/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'Profile' => 'user#Profile'

  get 'Dashboard' => 'user#Dashboard'

  get 'MySkills' => 'user#MySkills'

  get 'Home' => 'static_pages#Home'

  get 'About' => 'static_pages#About'

  get 'Help' => 'static_pages#Help'

  get 'Settings' => 'static_pages#Settings'

  resources :development_plans
  resources :development_skills
  resources :skills
  resources :development_tasks
  resources :skill_categories
  resources :skill_levels

  root 'static_pages#Home'

end

nils_2_skills/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_many :development_plans
  has_many :development_skills

  def my_skills
    development_skills.where(completed: true).all.uniq
  end
end

nils_2_skills/app/controllers/user_controller.rb
class UserController < ApplicationController

  def dashboard
  end

  def profile
  end

  def my_skills
    @my_skills = current_user.my_skills
  end
end

nils_2_skills/app/helpers/user_helper.rb
module UserHelper
end

nils_2_skills/app/views/user/Dashboard.html.erb
<h1>User#Dashboard</h1>
<p>Find me in app/views/user/Dashboard.html.erb</p>

<% if current_user.development_plans.any? %>
	<% current_user.development_plans.each do |plan| %>
		Plan Name: <%= link_to("#{plan.plan_name}", development_plan_path(plan.id)) %> <br/><br/>
	<% end %>
	<br/><%= link_to("Create a new development plan", new_development_plan_path) %>
<% else %>
	<%= current_user.username %> does not currently have any development plans!
	<%= link_to("Create a new development plan", new_development_plan_path) %>
<% end %>

nils_2_skills/app/views/user/MySkills.html.erb
<h1>My Skills</h1>
<br/>
<table>
	<tr>
		<td>Skill</td>
	</tr>
	<% @my_skills.each do |skill| %>
	    <tr>
	      <td><%= skill.skill_name %></td>
	    </tr>
	<% end %>
</table>
<br/>
<%= link_to 'New Development skill', new_development_skill_path %>

nils_2_skills/app/views/user/Profile.html.erb
<h1>User#Profile</h1>
<p>Find me in app/views/user/Profile.html.erb</p>