nils_2_skills/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'Profile' => 'user#Profile'

  get 'Dashboard' => 'user#Dashboard'

  get 'MySkills' => 'user#MySkills'

  get 'Home' => 'static_pages#Home'

  get 'About' => 'static_pages#About'

  get 'Help' => 'static_pages#Help'

  get 'Settings' => 'static_pages#Settings'

  resources :development_plans
  resources :development_skills
  resources :skills
  resources :development_tasks
  resources :skill_categories
  resources :skill_levels

  root 'static_pages#Home'

end

nils_2_skills/app/models/skill.rb
class Skill < ActiveRecord::Base
  #validates :skill_id, presence: true
  #validates :category, presence: true

  has_many :development_skills
  has_and_belongs_to_many :skill_categories
end

nils_2_skills/app/controllers/skill_controller.rb
class SkillController < ApplicationController
  def new
  	@skill = Skill.new
  end

  def create
  	@skill = Skill.new(skill_params)
	  	if @skill.save
	  	  redirect_to :Dashboard
	  	else
	      redirect_to skill_new_path
	  end
  end

  def destroy
  	@skill.destroy
  	redirect_to 'Dashboard'
  end

  def edit
  end

  def skill_params
  	params.require(:skill).permit(:skill_name, :category, :description)
  end
end

nils_2_skills/app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  def new
    @skill = Skill.new
  end

  def show
  end

  def index
    @skills = Skill.all
  end

  def create
    @skill = Skill.new(skill_params)
    if @skill.save
      redirect_to skills_path
    else
      redirect_to skill_new_path
    end
  end

  def destroy
    @skill.destroy
    redirect_to skills_path
  end

  def edit
  end

  def update
    @skill.update(skill_params)
    redirect_to skills_path
  end

  def set_skill
    @skill = Skill.find(params[:id])
  end

  def skill_params
    params.require(:skill).permit(:skill_name, :category, :description)
  end
end

nils_2_skills/app/helpers/skill_helper.rb
module SkillHelper
end

nils_2_skills/app/views/skills/_form.html.erb
<%= form_for (@skill) do |s| %>

  <% if @skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skill.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= s.label :skill_name %>:
  <%= s.text_field :skill_name, class: 'form-control'%><br/>

  <%= s.label :category %>:
  <%= collection_select(:skill, :category, SkillCategory.all, :id, :category_name) %>
  <%= link_to "Create a new category", new_skill_category_path %><br/>

  <%= s.label :description %>:
  <%= s.text_area :description, class: 'form-control'%>

    <div class="actions">
    <%= s.submit %>
  </div>

<% end %>

nils_2_skills/app/views/skills/edit.html.erb
<h1>Edit Skill</h1>

<%= render 'form' %>

<%= link_to("Back to skills", skills_path) %>

nils_2_skills/app/views/skills/index.html.erb
<h1>Listing skills</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Description</th>
  </tr>

    <% @skills.each do |skill| %>
      <tr>
        <td><%= link_to("#{skill.skill_name}", skill_path(skill.id)) %></td>
        <td><%= SkillCategory.find(skill.category).category_name %></td>
        <td><%= skill.description %></td>
        <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
        <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
</table>

<br>

<%= link_to 'New Skill', new_skill_path %>

nils_2_skills/app/views/skills/new.html.erb
<h1>Create a skill!</h1>

<%= render 'form' %>

nils_2_skills/app/views/skills/show.html.erb
<h1>Show</h1>

Skill Name: <%=  @skill.skill_name %><br/>
Category: <%= SkillCategory.find(@skill.category).category_name %><br/>
Description: <%= @skill.description %><br/>
<%= link_to("edit", edit_skill_path(@skill.id)) %> <br/>
<%= link_to "delete?", @skill, method: :delete, data: { confirm: "Are you sure you want to delete the task #{@skill.skill_name}?"} %><br/><br/>

<br/><br/>
<%= link_to("Back to Dashboard", :Dashboard) %>