nils_2_skills/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'Profile' => 'user#Profile'

  get 'Dashboard' => 'user#Dashboard'

  get 'MySkills' => 'user#MySkills'

  get 'Home' => 'static_pages#Home'

  get 'About' => 'static_pages#About'

  get 'Help' => 'static_pages#Help'

  get 'Settings' => 'static_pages#Settings'

  resources :development_plans
  resources :development_skills
  resources :skills
  resources :development_tasks
  resources :skill_categories
  resources :skill_levels

  root 'static_pages#Home'

end

nils_2_skills/app/models/skill_level.rb
class SkillLevel < ActiveRecord::Base
  validates :level, presence: true
  validates :level, uniqueness: true
  has_many :desired_skill_levels, foreign_key: 'desired_skill_level_id', class_name: 'DevelopmentSkill'
  has_many :current_skill_levels, foreign_key: 'current_skill_level_id', class_name: 'DevelopmentSkill'
end

nils_2_skills/app/controllers/skill_levels_controller.rb
class SkillLevelsController < ApplicationController
  before_action :set_skill_level, only: [:show, :edit, :update, :destroy]

  # GET /skill_levels
  # GET /skill_levels.json
  def index
    @skill_levels = SkillLevel.all
  end

  # GET /skill_levels/new
  def new
    @skill_level = SkillLevel.new
  end

  # GET /skill_levels/1/edit
  def edit
  end

  def show
  end

  # POST /skill_levels
  # POST /skill_levels.json
  def create
    @skill_level = SkillLevel.new(skill_level_params)

    respond_to do |format|
      if @skill_level.save
        format.html { redirect_to @skill_level, notice: 'Skill level was successfully created.' }
        format.json { render :show, status: :created, location: @skill_level }
      else
        format.html { render :new }
        format.json { render json: @skill_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skill_levels/1
  # PATCH/PUT /skill_levels/1.json
  def update
    respond_to do |format|
      if @skill_level.update(skill_level_params)
        format.html { redirect_to @skill_level, notice: 'Skill level was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill_level }
      else
        format.html { render :edit }
        format.json { render json: @skill_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skill_levels/1
  # DELETE /skill_levels/1.json
  def destroy
    @skill_level.destroy
    respond_to do |format|
      format.html { redirect_to skill_levels_url, notice: 'Skill level was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_skill_level
    @skill_level = SkillLevel.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def skill_level_params
    params.require(:skill_level).permit(:level, :description)
  end
end

nils_2_skills/app/helpers/skill_levels_helper.rb
module SkillLevelsHelper
end

nils_2_skills/app/views/skill_levels/_form.html.erb
<%= form_for(@skill_level) do |f| %>
  <% if @skill_level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skill_level.errors.count, "error") %> prohibited this skill_level from being saved:</h2>

      <ul>
      <% @skill_level.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :level %>
    <%= f.text_field :level, class: 'form-control' %>

    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

nils_2_skills/app/views/skill_levels/edit.html.erb
<h1>Editing skill_level</h1>

<%= render 'form' %>

<%= link_to 'Show', @skill_level %> |
<%= link_to 'Back', skill_levels_path %>

nils_2_skills/app/views/skill_levels/index.html.erb
<h1>Listing skill_levels</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skill_levels.each do |skill_level| %>
      <tr>
        <td><%= skill_level.level %></td>
        <td><%= skill_level.description %></td>
        <td><%= link_to 'Edit', edit_skill_level_path(skill_level) %></td>
        <td><%= link_to 'Destroy', skill_level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill level', new_skill_level_path %>

nils_2_skills/app/views/skill_levels/new.html.erb
<h1>New skill_level</h1>

<%= render 'form' %>

<%= link_to 'Back', skill_levels_path %>

nils_2_skills/app/views/skill_levels/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_skill_level_path(@skill_level) %> |
<%= link_to 'Back', skill_levels_path %>